// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellerProto.proto

package via.sep3.persistencetier.protobuf;

public interface AddressModelSellerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seller.AddressModelSeller)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string streetName = 2;</code>
   * @return The streetName.
   */
  java.lang.String getStreetName();
  /**
   * <code>string streetName = 2;</code>
   * @return The bytes for streetName.
   */
  com.google.protobuf.ByteString
      getStreetNameBytes();

  /**
   * <code>int32 postCode = 3;</code>
   * @return The postCode.
   */
  int getPostCode();
}
