// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellerProto.proto

package via.sep3.persistencetier.protobuf;

public interface CreateSellerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSellerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CreateUserModelResponse user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.CreateUserModelResponse user = 1;</code>
   * @return The user.
   */
  via.sep3.persistencetier.protobuf.CreateUserModelResponse getUser();
  /**
   * <code>.CreateUserModelResponse user = 1;</code>
   */
  via.sep3.persistencetier.protobuf.CreateUserModelResponseOrBuilder getUserOrBuilder();

  /**
   * <code>int32 cvr = 2;</code>
   * @return The cvr.
   */
  int getCvr();

  /**
   * <code>string companyName = 3;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 3;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string type = 5;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string website = 6;</code>
   * @return The website.
   */
  java.lang.String getWebsite();
  /**
   * <code>string website = 6;</code>
   * @return The bytes for website.
   */
  com.google.protobuf.ByteString
      getWebsiteBytes();

  /**
   * <code>float rating = 7;</code>
   * @return The rating.
   */
  float getRating();
}
