// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package via.sep3.persistencetier.protobuf;

public interface CreateCustomerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:customer.CreateCustomerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.customer.CreateUserModelRequestCustomer user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.customer.CreateUserModelRequestCustomer user = 1;</code>
   * @return The user.
   */
  via.sep3.persistencetier.protobuf.CreateUserModelRequestCustomer getUser();
  /**
   * <code>.customer.CreateUserModelRequestCustomer user = 1;</code>
   */
  via.sep3.persistencetier.protobuf.CreateUserModelRequestCustomerOrBuilder getUserOrBuilder();

  /**
   * <code>repeated string preference = 2;</code>
   * @return A list containing the preference.
   */
  java.util.List<java.lang.String>
      getPreferenceList();
  /**
   * <code>repeated string preference = 2;</code>
   * @return The count of preference.
   */
  int getPreferenceCount();
  /**
   * <code>repeated string preference = 2;</code>
   * @param index The index of the element to return.
   * @return The preference at the given index.
   */
  java.lang.String getPreference(int index);
  /**
   * <code>repeated string preference = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the preference at the given index.
   */
  com.google.protobuf.ByteString
      getPreferenceBytes(int index);
}
