// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package via.sep3.persistencetier.protobuf;

public interface CustomerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:customer.CustomerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
