// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package via.sep3.persistencetier.protobuf;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_AddressModelCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_AddressModelCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_UserModelResponseCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_UserModelResponseCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CreateUserModelRequestCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CreateUserModelRequestCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CreateCustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CreateCustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CustomerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CustomerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CustomerProto.proto\022\010customer\" \n\017Custo" +
      "merRequest\022\r\n\005email\030\001 \001(\t\"J\n\024AddressMode" +
      "lCustomer\022\014\n\004city\030\001 \001(\t\022\022\n\nstreetName\030\002 " +
      "\001(\t\022\020\n\010postCode\030\003 \001(\005\"\225\001\n\031UserModelRespo" +
      "nseCustomer\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastNa" +
      "me\030\002 \001(\t\022/\n\007address\030\003 \001(\0132\036.customer.Add" +
      "ressModelCustomer\022\023\n\013phoneNumber\030\004 \001(\005\022\r" +
      "\n\005email\030\005 \001(\t\"\232\001\n\036CreateUserModelRequest" +
      "Customer\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030" +
      "\002 \001(\t\022/\n\007address\030\003 \001(\0132\036.customer.Addres" +
      "sModelCustomer\022\023\n\013phoneNumber\030\004 \001(\005\022\r\n\005e" +
      "mail\030\005 \001(\t\"c\n\025CreateCustomerRequest\0226\n\004u" +
      "ser\030\001 \001(\0132(.customer.CreateUserModelRequ" +
      "estCustomer\022\022\n\npreference\030\002 \001(\t\"Y\n\020Custo" +
      "merResponse\0221\n\004user\030\001 \001(\0132#.customer.Use" +
      "rModelResponseCustomer\022\022\n\npreference\030\002 \001" +
      "(\t2\375\001\n\017CustomerService\022M\n\016createCustomer" +
      "\022\037.customer.CreateCustomerRequest\032\032.cust" +
      "omer.CustomerResponse\022K\n\022getCustomerByEm" +
      "ail\022\031.customer.CustomerRequest\032\032.custome" +
      "r.CustomerResponse\022N\n\025deleteCustomerByEm" +
      "ail\022\031.customer.CustomerRequest\032\032.custome" +
      "r.CustomerResponseB%\n!via.sep3.persisten" +
      "cetier.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_customer_CustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_customer_CustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CustomerRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_customer_AddressModelCustomer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_customer_AddressModelCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_AddressModelCustomer_descriptor,
        new java.lang.String[] { "City", "StreetName", "PostCode", });
    internal_static_customer_UserModelResponseCustomer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_customer_UserModelResponseCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_UserModelResponseCustomer_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", "PhoneNumber", "Email", });
    internal_static_customer_CreateUserModelRequestCustomer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_customer_CreateUserModelRequestCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CreateUserModelRequestCustomer_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", "PhoneNumber", "Email", });
    internal_static_customer_CreateCustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_customer_CreateCustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CreateCustomerRequest_descriptor,
        new java.lang.String[] { "User", "Preference", });
    internal_static_customer_CustomerResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_customer_CustomerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CustomerResponse_descriptor,
        new java.lang.String[] { "User", "Preference", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
