// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package via.sep3.persistencetier.protobuf;

public interface CustomerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:customer.CustomerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.customer.UserModelResponseCustomer user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.customer.UserModelResponseCustomer user = 1;</code>
   * @return The user.
   */
  via.sep3.persistencetier.protobuf.UserModelResponseCustomer getUser();
  /**
   * <code>.customer.UserModelResponseCustomer user = 1;</code>
   */
  via.sep3.persistencetier.protobuf.UserModelResponseCustomerOrBuilder getUserOrBuilder();

  /**
   * <code>string preference = 2;</code>
   * @return The preference.
   */
  java.lang.String getPreference();
  /**
   * <code>string preference = 2;</code>
   * @return The bytes for preference.
   */
  com.google.protobuf.ByteString
      getPreferenceBytes();
}
