// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package via.sep3.persistencetier.protobuf;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_EmptyCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_EmptyCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_AddressModelCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_AddressModelCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_UserModelResponseCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_UserModelResponseCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CreateUserModelRequestCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CreateUserModelRequestCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CreateCustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CreateCustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CustomerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CustomerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CustomerProto.proto\022\010customer\"\017\n\rEmpty" +
      "Customer\" \n\017CustomerRequest\022\r\n\005email\030\001 \001" +
      "(\t\"J\n\024AddressModelCustomer\022\014\n\004city\030\001 \001(\t" +
      "\022\022\n\nstreetName\030\002 \001(\t\022\020\n\010postCode\030\003 \001(\005\"\225" +
      "\001\n\031UserModelResponseCustomer\022\021\n\tfirstNam" +
      "e\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022/\n\007address\030\003 \001" +
      "(\0132\036.customer.AddressModelCustomer\022\023\n\013ph" +
      "oneNumber\030\004 \001(\005\022\r\n\005email\030\005 \001(\t\"\254\001\n\036Creat" +
      "eUserModelRequestCustomer\022\021\n\tfirstName\030\001" +
      " \001(\t\022\020\n\010lastName\030\002 \001(\t\022/\n\007address\030\003 \001(\0132" +
      "\036.customer.AddressModelCustomer\022\023\n\013phone" +
      "Number\030\004 \001(\005\022\r\n\005email\030\005 \001(\t\022\020\n\010password\030" +
      "\006 \001(\t\"c\n\025CreateCustomerRequest\0226\n\004user\030\001" +
      " \001(\0132(.customer.CreateUserModelRequestCu" +
      "stomer\022\022\n\npreference\030\002 \001(\t\"Y\n\020CustomerRe" +
      "sponse\0221\n\004user\030\001 \001(\0132#.customer.UserMode" +
      "lResponseCustomer\022\022\n\npreference\030\002 \001(\t2\307\002" +
      "\n\017CustomerService\022M\n\016createCustomer\022\037.cu" +
      "stomer.CreateCustomerRequest\032\032.customer." +
      "CustomerResponse\022K\n\022getCustomerByEmail\022\031" +
      ".customer.CustomerRequest\032\032.customer.Cus" +
      "tomerResponse\022N\n\025deleteCustomerByEmail\022\031" +
      ".customer.CustomerRequest\032\032.customer.Cus" +
      "tomerResponse\022H\n\017getAllCustomers\022\027.custo" +
      "mer.EmptyCustomer\032\032.customer.CustomerRes" +
      "ponse0\001B%\n!via.sep3.persistencetier.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_customer_EmptyCustomer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_customer_EmptyCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_EmptyCustomer_descriptor,
        new java.lang.String[] { });
    internal_static_customer_CustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_customer_CustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CustomerRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_customer_AddressModelCustomer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_customer_AddressModelCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_AddressModelCustomer_descriptor,
        new java.lang.String[] { "City", "StreetName", "PostCode", });
    internal_static_customer_UserModelResponseCustomer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_customer_UserModelResponseCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_UserModelResponseCustomer_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", "PhoneNumber", "Email", });
    internal_static_customer_CreateUserModelRequestCustomer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_customer_CreateUserModelRequestCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CreateUserModelRequestCustomer_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", "PhoneNumber", "Email", "Password", });
    internal_static_customer_CreateCustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_customer_CreateCustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CreateCustomerRequest_descriptor,
        new java.lang.String[] { "User", "Preference", });
    internal_static_customer_CustomerResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_customer_CustomerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CustomerResponse_descriptor,
        new java.lang.String[] { "User", "Preference", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
