// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package via.sep3.persistencetier.protobuf;

public interface EmptyCustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:customer.EmptyCustomer)
    com.google.protobuf.MessageOrBuilder {
}
