// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellerProto.proto

package via.sep3.persistencetier.protobuf;

public interface EmptySellerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seller.EmptySeller)
    com.google.protobuf.MessageOrBuilder {
}
