// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodPack.proto

package via.sep3.persistencetier.protobuf;

public interface EmptyPackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:packPackage.EmptyPack)
    com.google.protobuf.MessageOrBuilder {
}
