// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodPack.proto

package via.sep3.persistencetier.protobuf;

public final class FoodPack {
  private FoodPack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packPackage_createFoodPackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packPackage_createFoodPackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packPackage_EmptyPack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packPackage_EmptyPack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packPackage_searchFoodPacks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packPackage_searchFoodPacks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packPackage_foodPackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packPackage_foodPackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packPackage_foodPackRespons_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packPackage_foodPackRespons_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016FoodPack.proto\022\013packPackage\"y\n\025createF" +
      "oodPackRequest\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(" +
      "\t\022\023\n\013description\030\003 \001(\t\022\023\n\013is_prepared\030\004 " +
      "\001(\010\022\r\n\005price\030\005 \001(\001\022\014\n\004type\030\006 \001(\t\"\013\n\tEmpt" +
      "yPack\"d\n\017searchFoodPacks\022\023\n\013is_prepared\030" +
      "\001 \001(\010\022\r\n\005title\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\r\n\005pr" +
      "ice\030\004 \001(\001\022\020\n\010postcode\030\005 \001(\005\"\035\n\017foodPackR" +
      "equest\022\n\n\002id\030\001 \001(\005\"s\n\017foodPackRespons\022\n\n" +
      "\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030" +
      "\003 \001(\t\022\023\n\013is_prepared\030\004 \001(\010\022\r\n\005price\030\005 \001(" +
      "\001\022\014\n\004type\030\006 \001(\t2\315\002\n\017FoodPackService\022R\n\016c" +
      "reateFoodPack\022\".packPackage.createFoodPa" +
      "ckRequest\032\034.packPackage.foodPackRespons\022" +
      "M\n\017getFoodPackById\022\034.packPackage.foodPac" +
      "kRequest\032\034.packPackage.foodPackRespons\022I" +
      "\n\017searchFoodPacks\022\026.packPackage.EmptyPac" +
      "k\032\034.packPackage.foodPackRespons0\001\022L\n\016del" +
      "eteFoodPack\022\034.packPackage.foodPackReques" +
      "t\032\034.packPackage.foodPackResponsB%\n!via.s" +
      "ep3.persistencetier.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_packPackage_createFoodPackRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packPackage_createFoodPackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packPackage_createFoodPackRequest_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "IsPrepared", "Price", "Type", });
    internal_static_packPackage_EmptyPack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_packPackage_EmptyPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packPackage_EmptyPack_descriptor,
        new java.lang.String[] { });
    internal_static_packPackage_searchFoodPacks_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_packPackage_searchFoodPacks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packPackage_searchFoodPacks_descriptor,
        new java.lang.String[] { "IsPrepared", "Title", "Type", "Price", "Postcode", });
    internal_static_packPackage_foodPackRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_packPackage_foodPackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packPackage_foodPackRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_packPackage_foodPackRespons_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_packPackage_foodPackRespons_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packPackage_foodPackRespons_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "IsPrepared", "Price", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
