// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellerProto.proto

package via.sep3.persistencetier.protobuf;

public interface ImageModelRequestSellerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seller.ImageModelRequestSeller)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string imageUrl = 1;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string imageUrl = 1;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
