// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellerProto.proto

package via.sep3.persistencetier.protobuf;

public interface SellerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seller.SellerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cvr = 1;</code>
   * @return The cvr.
   */
  int getCvr();
}
