// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellerProto.proto

package via.sep3.persistencetier.protobuf;

public interface UserModelResponseSellerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:seller.UserModelResponseSeller)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>.seller.AddressModelSeller address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.seller.AddressModelSeller address = 3;</code>
   * @return The address.
   */
  via.sep3.persistencetier.protobuf.AddressModelSeller getAddress();
  /**
   * <code>.seller.AddressModelSeller address = 3;</code>
   */
  via.sep3.persistencetier.protobuf.AddressModelSellerOrBuilder getAddressOrBuilder();

  /**
   * <code>int32 phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  int getPhoneNumber();

  /**
   * <code>string email = 5;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
